// Mocks generated by Mockito 5.4.4 from annotations
// in elevate_ecommerce/test/features/payment/data/repos/payment_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_ecommerce/core/common/api_result.dart' as _i4;
import 'package:elevate_ecommerce/features/payment/data/contracts/payment_online_datasource.dart'
    as _i2;
import 'package:elevate_ecommerce/features/payment/data/models/payment/payment.dart'
    as _i5;
import 'package:elevate_ecommerce/features/payment/data/models/request/payment/payment.request.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PaymentOnlineDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentOnlineDatasource extends _i1.Mock
    implements _i2.PaymentOnlineDatasource {
  MockPaymentOnlineDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.Payment?>> getPayment(
          _i6.PaymentRequest? paymentRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPayment,
          [paymentRequest],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Payment?>>.value(
            _i7.dummyValue<_i4.Result<_i5.Payment?>>(
          this,
          Invocation.method(
            #getPayment,
            [paymentRequest],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Payment?>>);
}
