// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVsiDMq6GEfnpJMjCVCHguXX5duZaOOe8',
    appId: '1:98645490250:web:ab003e29faea48a1f344b3',
    messagingSenderId: '98645490250',
    projectId: 'elevateflowery',
    authDomain: 'elevateflowery.firebaseapp.com',
    storageBucket: 'elevateflowery.firebasestorage.app',
    measurementId: 'G-N096TMN5HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ5epvp-9QLU-3OtQmiraTW07fzvLbDo0',
    appId: '1:98645490250:android:f8c87c19e21e1efbf344b3',
    messagingSenderId: '98645490250',
    projectId: 'elevateflowery',
    storageBucket: 'elevateflowery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3rh9RD2-FWgZA9zQf2guvBI5sDHldqdo',
    appId: '1:98645490250:ios:cbe37e0809f0da47f344b3',
    messagingSenderId: '98645490250',
    projectId: 'elevateflowery',
    storageBucket: 'elevateflowery.firebasestorage.app',
    iosClientId: '98645490250-mfps3pribkv6ledh69app94elqkjv0sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.elevateEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3rh9RD2-FWgZA9zQf2guvBI5sDHldqdo',
    appId: '1:98645490250:ios:cbe37e0809f0da47f344b3',
    messagingSenderId: '98645490250',
    projectId: 'elevateflowery',
    storageBucket: 'elevateflowery.firebasestorage.app',
    iosClientId: '98645490250-mfps3pribkv6ledh69app94elqkjv0sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.elevateEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVsiDMq6GEfnpJMjCVCHguXX5duZaOOe8',
    appId: '1:98645490250:web:3ab36dfd6fd95a61f344b3',
    messagingSenderId: '98645490250',
    projectId: 'elevateflowery',
    authDomain: 'elevateflowery.firebaseapp.com',
    storageBucket: 'elevateflowery.firebasestorage.app',
    measurementId: 'G-M57YQTVJPP',
  );
}
