// Mocks generated by Mockito 5.4.4 from annotations
// in elevate_ecommerce/test/features/Cart/domain/usecases/get_cart_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elevate_ecommerce/core/common/api_result.dart' as _i4;
import 'package:elevate_ecommerce/features/Cart/domain/model/cart_model.dart'
    as _i5;
import 'package:elevate_ecommerce/features/Cart/domain/repos/cart_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i2.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.CartModel?>> getAllCart() => (super.noSuchMethod(
        Invocation.method(
          #getAllCart,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.CartModel?>>.value(
            _i6.dummyValue<_i4.Result<_i5.CartModel?>>(
          this,
          Invocation.method(
            #getAllCart,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.CartModel?>>);

  @override
  _i3.Future<_i4.Result<bool?>> addProductToCart(
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProductToCart,
          [
            productId,
            quantity,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<bool?>>.value(
            _i6.dummyValue<_i4.Result<bool?>>(
          this,
          Invocation.method(
            #addProductToCart,
            [
              productId,
              quantity,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<bool?>>);

  @override
  _i3.Future<_i4.Result<_i5.CartModel?>> updateCartProductQuantity(
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartProductQuantity,
          [
            productId,
            quantity,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.CartModel?>>.value(
            _i6.dummyValue<_i4.Result<_i5.CartModel?>>(
          this,
          Invocation.method(
            #updateCartProductQuantity,
            [
              productId,
              quantity,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.CartModel?>>);

  @override
  _i3.Future<_i4.Result<bool?>> removeItemFromCart(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeItemFromCart,
          [productId],
        ),
        returnValue: _i3.Future<_i4.Result<bool?>>.value(
            _i6.dummyValue<_i4.Result<bool?>>(
          this,
          Invocation.method(
            #removeItemFromCart,
            [productId],
          ),
        )),
      ) as _i3.Future<_i4.Result<bool?>>);
}
