name: Firebase App Distribution

on:
    pull_request:
      branches:
        - dev # Trigger workflow on pull requests targeting the dev branch
  

jobs:
  distribute-app:
    name: Distribute App to Firebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK (for Android builds)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter (for Flutter apps)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release # Change to 'ios' for iOS builds

    - name: Upload to Firebase App Distribution
      env:
        FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase appdistribution:distribute \
          build/app/outputs/flutter-apk/app-release.apk \ # Path to the APK
          --app 1:284880685668:android:25422020aa8c9f0ad46d71 \                      # Replace with your Firebase app ID
          --groups testers                   # Replace with your tester group
